### ISSUE TITLE
Withdrawal of npm package pimatic-plugin-ethboard

### ISSUE THREAD

**Issue by mwittig** [mplessing/pimatic-ethboard#1]
Hi Markus, 

Dein Plugin taucht in Pimatic zweimal in Pimatic auf. Könntest Du bitte mal das veraltete Paket 'pimatic-plugin-ethboard' bei npmjs löschen. Ich bin mir nicht sicher, ob diese noch via unpublish möglich ist, notfalls müsstest Du an den Support schreiben. Die Alternative "deprecate" passt hier nicht so gut, denke ich. 

https://docs.npmjs.com/cli/unpublish

**Comment by mplessing** [comment]
Hi Marcus,

ja, das wollte ich schon lange mal machen. 
Jedenfalls ist das Paket jetzt nicht mehr auf npm verfügbar und wird bei den installierbaren Plugins auch nicht mehr aufgeführt. 

Auf der pimatic.org Seite ist es aber noch gelistet. Das kannst ja vllt. du oder sweetpi entsprechend ändern, wenn es nicht automatisch verschwindet.

Danke für die Erinnerung.

Markus

**Comment by mwittig** [comment]
Hi Markus, 

Danke für Deine schnelle Bearbeitung!

> Auf der pimatic.org Seite ist es aber noch gelistet. 

Ich behalte das im Auge. Die Seite wir täglich neu generiert, aber manchmal hängt sich der Update-Prozeß auf. Schauen wir mal.

Marcus
